/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.VendaEmprestimo.lproe;
import static View.VendaEmprestimo.lprov;
import controller.ProdutoJpaController;
import controller.VendaJpaController;
import controller.ClienteJpaController;
import controller.DetalorgJpaController;
import controller.EmprestimoJpaController;
import controller.EntradaJpaController;
import controller.VendedorJpaController;
import controller.exceptions.NonexistentEntityException;
import java.io.File;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import metodos.ValidarFloat;
import metodos.ValidarInteiro;
import metodos.ValidarString;
import modelo.Produto;
import modelo.Cliente;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManager;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;
import modelo.Detalorg;
import modelo.Emprestimo;
import modelo.Entrada;
import modelo.Venda;
import modelo.Vendedor;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;

/**
 *
 * @author Ussimane
 */
public class EmpData extends javax.swing.JDialog {

    /**
     * Creates new form FormProduto
     */
    EntityManagerFactory emf = new metodos.ControllerAcess().getEntityManagerFactory();
    private static List<Produto> p;
    private static List<Produto> pv;
    private static List<Entrada> le;
    private static Date d;
    private static Cliente cli;
    private static String no;
    private static String nu;
    private static int v, desc;
    Detalorg dog = new Detalorg();
    JasperPrint jpPrint;
    Map parametros = new HashMap<>();
    private static String impvenda;

    public EmpData(java.awt.Frame parent, List<Produto> pv, List<Entrada> le, List<Produto> p, Date d, Cliente n, int v, int desc, String no, String imp, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagens/sas.png")).getImage());
        this.p = p;
        this.d = d;
        this.cli = n;
        this.le = le;
        this.impvenda = imp;
        Date dd = new Date();
        Calendar cal = new GregorianCalendar();
        cal.setTime(dd);
        cal.set(Calendar.DAY_OF_MONTH, 1);
        Date nn = cal.getTime();
        dpag.setDate(nn);
        dog = new DetalorgJpaController(emf).findDetalorgEntities().get(0);
        // this.nu = nu;
        this.v = v;
        this.desc = desc;
        this.no = no;
        this.pv = pv;
        txtIdP.setVisible(false);
        lbValidacao.setVisible(false);
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(jButton1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtIdP = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        lbValidacao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dpag = new com.toedter.calendar.JDateChooser();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(getLimpaVenda());
        setName("dialogProd"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_ok.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitle.setText("                                     Venda a credito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        lbValidacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValidacao.setForeground(new java.awt.Color(255, 51, 51));
        lbValidacao.setText("jLabel4");

        jLabel3.setText("Data de Pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dpag, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValidacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dpag.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione a data de pagamento", "Atencao", JOptionPane.WARNING_MESSAGE);
            dpag.grabFocus();
            return;
        }

//        new SwingWorker() {
//            @Override
//            protected Object doInBackground() throws Exception {
        PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
        PrintService printService = null;
        //System.out.println(printServices.length + "");
        for (PrintService ps : printServices) {
            if (ps.getName().equals(impvenda)) {
                printService = ps;
                break;
            }
        }
        if (printService == null) {
            JOptionPane.showMessageDialog(this, "A impressora " + impvenda + "nao foi encontrada\n"
                    + "por favor configure um nome valido", "Atencao", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Date d = new Date();
        //int desc = n.getIdempresa().getDesconto();
        float tde = 0;
        float tvp = 0;
        float tiv = 0;
        EntityManager em = emf.createEntityManager();
        try {
            EntradaJpaController ec = new EntradaJpaController(emf);
            List<Entrada> lsord = new ArrayList<Entrada>();
        lsord.addAll(le);
        int n = lsord.size();
        for (int p = 0; p < n - 1; p++) {
            for (int i = 0; i < n - p - 1; i++) {
                if (lsord.get(i).getEntradaPK().getData().after(lsord.get(i + 1).getEntradaPK().getData())) {
                    Entrada aux = lsord.get(i);
                    lsord.set(i, lsord.get(i + 1));
                    lsord.set(i + 1, aux);
                }
            }
        }
            em.getTransaction().begin();
            for (Entrada p : lsord) {
                int q = ec.editVenda(p, em);
                if (q > 0) {
                    JOptionPane.showMessageDialog(this, p.getProduto().getNome() + "\n"
                            + "A quantidade seleccionada e maior que a quantidade disponivel", "Atencao", JOptionPane.WARNING_MESSAGE);
                    // em.getTransaction().rollback();
                    em.clear();
                    em.getTransaction().commit();
                    return;
                }
            }
            for (Produto p : pv) {
                new ProdutoJpaController(emf).editVenda(p, em);
            }
            for (Produto p : p) {
                float valo = p.getPrecovenda() * p.getQtdvenda();
                float de = new Double(Math.ceil((new Integer(desc).floatValue() / 100) * valo)).floatValue();
                float imp = new Double(Math.ceil((p.getIdimposto().getPerc().floatValue() / 100) * valo)).floatValue();
                float vp = valo - de;
                tde = tde + de;
                tvp = tvp + vp;
                tiv = tiv + imp;
                Emprestimo e = new Emprestimo();
                e.setDataemprestimo(d);
                e.setDatapagamento(dpag.getDate());
                e.setIdcliente(cli);
                e.setDesconto(desc);
                e.setIdproduto(p);
                e.setIdvendedor(new Vendedor(v));
                e.setQtprod(p.getQtdvenda());
                e.setTotalpagar(vp);
                e.setIva(p.getIdimposto().getPerc());
                e.setTdesc(de);
                e.setTiva(imp);
                e.setDatae(p.getDataexpiracao());
                e.setQc(p.getQitem());
                e.setPrec(p.getPrecovenda());
                e.setQstock(p.getQtstock());
                e.setQpac(p.getMargem().intValue());
                new EmprestimoJpaController(emf).create(e, em);
            }
            em.getTransaction().commit();
        } catch (Exception ex) {
            em.clear();
            em.getTransaction().commit();
            Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (em != null) {
                em.close();
            }
        }
        parametros.clear();

        parametros.put("cli", cli.getNome());
        parametros.put("nuit", cli.getIdempresa().getNuite());
        parametros.put("data", d);
        parametros.put("org", dog.getOrg());
        parametros.put("end", dog.getEnde());
        // parametros.put("dir", dog.getDir());
        parametros.put("nif", dog.getNif());
        parametros.put("cid", dog.getCid());
        parametros.put("tel", dog.getTel());
        parametros.put("tde", tde + "(" + desc + "%)");
        parametros.put("tiv", tiv);
        parametros.put("tvp", tvp);
        parametros.put("ven", new VendedorJpaController(emf).findVendedor(v).getNomecompleto());

        String imge = new File("saslogo.png").getAbsolutePath();
        parametros.put("img", imge);
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(lproe);
        String path = new File("relatorios/recibo.jasper").getAbsolutePath();

        JasperPrint jasperPrint = null;
        try {
            jasperPrint = JasperFillManager.fillReport(path, parametros, ds);
        } catch (JRException ex) {
            Logger.getLogger(VendaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrintRequestAttributeSet printRequestAttributeSet = new HashPrintRequestAttributeSet();
        // printRequestAttributeSet.add(new Copies(2));
        JRExporter jrExporter = new JRPrintServiceExporter();
        jrExporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
        jrExporter.setParameter(JRPrintServiceExporterParameter.PRINT_REQUEST_ATTRIBUTE_SET, printRequestAttributeSet);
        jrExporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE, printService);
        jrExporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE_ATTRIBUTE_SET,
                printService.getAttributes());
        jrExporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PAGE_DIALOG, Boolean.FALSE);
        jrExporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PRINT_DIALOG, Boolean.FALSE);
        try {
            jrExporter.exportReport();
            jrExporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(EmpData.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro na Impressao \n"
                    + "por favor configure a Impressora", "Atencao", JOptionPane.WARNING_MESSAGE);
        }

//                return null;
//            }
//
//            @Override
//            protected void done() {
//            }
//        }.execute();
        this.setVisible(false);
        FormVenda f = new FormVenda(new javax.swing.JFrame(), jrExporter, true);
        f.setVisible(true);
       // JOptionPane.showMessageDialog(this, "Venda efectuada com Sucesso");

    }//GEN-LAST:event_jButton1ActionPerformed
    public void limpar() {
        dpag.setDate(new Date());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmpData dialog = new EmpData(new javax.swing.JFrame(), pv, le, p, d, cli, v, desc, no, impvenda, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public int getLimpaVenda() {

        return g();

    }

    public int g() {
        dpag.setDate(null);
        return 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dpag;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lbValidacao;
    private javax.swing.JTextField txtIdP;
    // End of variables declaration//GEN-END:variables
}
