/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;
import controller.ClienteJpaController;
import controller.EmpresaJpaController;
import controller.EntradaviaturaJpaController;
import controller.ModeloJpaController;
import controller.ProdutoJpaController;
import controller.VendaJpaController;
import controller.exceptions.NonexistentEntityException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import metodos.ValidarFloat;
import metodos.ValidarInteiro;
import metodos.ValidarString;
import modelo.Cliente;
import modelo.Empresa;
import modelo.Entradaviatura;
import modelo.Entradaviatura;
import modelo.Modelo;
import modelo.Produto;

/**
 *
 * @author Ussimane
 */
public class FormViatura extends javax.swing.JDialog {

    /**
     * Creates new form FormProduto
     */
    EntityManagerFactory emf = new metodos.ControllerAcess().getEntityManagerFactory();
    private static Entradaviatura p;
    private static String t;
    List<Cliente> listac = new ArrayList<>();
    List<Modelo> listaf = new ArrayList<>();
    AutoCompleteSupport support2 = null;
    AutoCompleteSupport support = null;

    public FormViatura(java.awt.Frame parent, Entradaviatura p, String t, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagens/sas.png")).getImage());
        //  this.setUndecorated(true);
        txtIdP.setVisible(false);
        this.setLocationRelativeTo(null);
        this.p = p;
        this.t = t;
        comboboxClient(jcClient);
        comboModelo(cbmodelo);
        labelTitle.setText(t);
        lbValidacao.setVisible(false);
        this.getRootPane().setDefaultButton(jButton1);
        if (p != null) {
            //Boolean b = new VendaJpaController(emf).getExistC(p);
            txtIdP.setText(p.getIdentrada() + "");
            txtMat.setText(p.getMatricula());
            cbmodelo.setSelectedItem(p.getModelo());
            jcClient.setSelectedItem(p.getCliente());
            txtnome.setText(p.getNomecliente());
            dent.setDate(p.getDataentrada());
            dsaida.setDate(p.getDatasaida());
            txtcor.setText(p.getCorviatura());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtIdP = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        lbValidacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbmodelo = new javax.swing.JComboBox();
        jcClient = new javax.swing.JComboBox();
        dent = new com.toedter.calendar.JDateChooser();
        dsaida = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        btadfam = new javax.swing.JButton();
        btedfam = new javax.swing.JButton();
        btdelfam = new javax.swing.JButton();
        btadimp = new javax.swing.JButton();
        btedimp = new javax.swing.JButton();
        btdelimp = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("dialogProd"); // NOI18N

        jLabel1.setText("Matricula:");

        jLabel3.setText("Cliente:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_ok.png"))); // NOI18N
        jButton1.setText("Aceitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        lbValidacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValidacao.setForeground(new java.awt.Color(255, 51, 51));
        lbValidacao.setText("jLabel4");

        jLabel4.setText("Data Entrada:");

        jLabel8.setText("Cor:");

        jLabel2.setText("Data Saida:");

        jLabel5.setText("Modelo:");

        cbmodelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbmodelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmodeloItemStateChanged(evt);
            }
        });

        jcClient.setMaximumRowCount(3);
        jcClient.setToolTipText("Seleccione ou pesquise cliente");
        jcClient.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcClientItemStateChanged(evt);
            }
        });
        jcClient.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jcClientInputMethodTextChanged(evt);
            }
        });
        jcClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcClientKeyReleased(evt);
            }
        });

        jLabel6.setText("Nome cliente:");

        btadfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_create.png"))); // NOI18N
        btadfam.setToolTipText("Adicionar nova familia");
        btadfam.setBorder(null);
        btadfam.setBorderPainted(false);
        btadfam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadfamActionPerformed(evt);
            }
        });

        btedfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ico_editar.png"))); // NOI18N
        btedfam.setToolTipText("Editar familia seleccionada");
        btedfam.setBorder(null);
        btedfam.setBorderPainted(false);
        btedfam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btedfamActionPerformed(evt);
            }
        });

        btdelfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ico_borrar.png"))); // NOI18N
        btdelfam.setToolTipText("Apagar familia sellecionada");
        btdelfam.setBorder(null);
        btdelfam.setBorderPainted(false);
        btdelfam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelfamActionPerformed(evt);
            }
        });

        btadimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bt_create.png"))); // NOI18N
        btadimp.setToolTipText("Adicionar novo imposto");
        btadimp.setBorder(null);
        btadimp.setBorderPainted(false);
        btadimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadimpActionPerformed(evt);
            }
        });

        btedimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ico_editar.png"))); // NOI18N
        btedimp.setToolTipText("Editar imposto seleccinado");
        btedimp.setBorder(null);
        btedimp.setBorderPainted(false);
        btedimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btedimpActionPerformed(evt);
            }
        });

        btdelimp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ico_borrar.png"))); // NOI18N
        btdelimp.setToolTipText("Apagar imposto seleccionado");
        btdelimp.setBorder(null);
        btdelimp.setBorderPainted(false);
        btdelimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelimpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmodelo, javax.swing.GroupLayout.Alignment.LEADING, 0, 343, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btadimp, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addComponent(btedimp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btdelimp)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dsaida, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnome)
                                    .addComponent(dent, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                            .addComponent(jcClient, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btadfam, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btedfam)
                .addGap(11, 11, 11)
                .addComponent(btdelfam)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbValidacao)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btedimp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdelimp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btadimp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jcClient))
                            .addComponent(btadfam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dsaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btedfam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdelfam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtMat.getText().trim().equals("")) {
            lbValidacao.setVisible(true);
            lbValidacao.setText("Instroduza a Matricula");
            txtMat.requestFocusInWindow();
            return;
        }
        if (!(cbmodelo.getSelectedItem()instanceof Modelo)) {
            lbValidacao.setVisible(true);
            lbValidacao.setText("Seleccione um modelo");
            cbmodelo.requestFocusInWindow();
            return;
        }

        if (txtcor.getText().trim().equals("")) {
            lbValidacao.setVisible(true);
            lbValidacao.setText("Introduza a cor da viatura");
            txtcor.requestFocusInWindow();
            return;
        }
        if (jcClient.getSelectedItem() == null) {
            lbValidacao.setVisible(true);
            lbValidacao.setText("Seleccione um cliente");
            jcClient.requestFocusInWindow();
            return;
        }

        if (txtIdP.getText().trim().equals("")) {
            EntradaviaturaJpaController cc = new EntradaviaturaJpaController(emf);

            Entradaviatura e = new Entradaviatura();
            //  pro.setNuit(txtNuit.getText());
            e.setMatricula(txtMat.getText());
            e.setModelo((Modelo) cbmodelo.getSelectedItem());
            e.setCliente((Cliente) jcClient.getSelectedItem());
            e.setNomecliente(txtnome.getText());
            e.setDataentrada(dent.getDate());
            e.setDatasaida(dsaida.getDate());
            e.setCorviatura(txtcor.getText());
            try {
                cc.create(e);
            } catch (Exception ex) {
                Logger.getLogger(FormViatura.class.getName()).log(Level.SEVERE, null, ex);
            }
            limpar();
            JOptionPane.showMessageDialog(this, "Adicionado com Sucesso");
        } else {
            int respo = JOptionPane.showOptionDialog(null, "Pretende modificar os dados deste Viatura?", "ATENÇÃO!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, new String[]{"SIM", "NÃO"}, null);
            if (respo == 1 || respo == -1) {
                return;
            }
            try {
                EntradaviaturaJpaController cc = new EntradaviaturaJpaController(emf);
                Entradaviatura e = cc.findEntradaviatura(Long.parseLong(txtIdP.getText()));
                //  pro.setNuit(txtNuit.getText());
                e.setMatricula(txtMat.getText());
                e.setModelo((Modelo) cbmodelo.getSelectedItem());
                e.setCorviatura(txtcor.getText());
                e.setCliente((Cliente) jcClient.getSelectedItem());
                e.setNomecliente(txtnome.getText());
                e.setDataentrada(dent.getDate());
                e.setDatasaida(dsaida.getDate());
                new EntradaviaturaJpaController(emf).edit(e);
                JOptionPane.showMessageDialog(this, "Editado com Sucesso");
                this.setVisible(false);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void limpar() {
        txtIdP.setText("");
        txtMat.setText("");
        txtnome.setText("");
        dent.setDate(null);
        dsaida.setDate(null);
        txtcor.setText("");
        lbValidacao.setVisible(false);
    }

    public void comboboxClient(JComboBox c) {
        listac = new ClienteJpaController(emf).getClientAsc();
        if (listac.isEmpty()) {
            return;
        }
        Cliente[] elements = listac.toArray(new Cliente[]{});
        support = AutoCompleteSupport.install(
                c, GlazedLists.eventListOf(elements));
    }

    public void comboModelo(JComboBox c) {
        listaf = new ModeloJpaController(emf).getModeloAsc();
        if (listaf.isEmpty()) {
            return;
        }
        Modelo[] elements = listaf.toArray(new Modelo[]{});
        support2 = AutoCompleteSupport.install(
                c, GlazedLists.eventListOf(elements));
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpar();
        this.getParent().setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbmodeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmodeloItemStateChanged
        //
        //        float i = 0;
        //        if (cbmodelo.getSelectedItem() != null) {
        //            i = ((Imposto) cbmodelo.getSelectedItem()).getPerc().floatValue() / 100;
        //        }
        //        if (!txtPreco.getText().trim().equals("")) {
        //            float p = Float.parseFloat(txtPreco.getText());
        //            if (p != 0) {
        //                lbpv.setText(String.valueOf(new Double(Math.ceil(p + (p * i))).floatValue()));
        //            }
        //        }
    }//GEN-LAST:event_cbmodeloItemStateChanged

    private void jcClientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcClientItemStateChanged
//        if (jcClient.getSelectedItem() == null) {
//            return;
//        }
//        Cliente c = (Cliente) jcClient.getSelectedItem();
//        tfcli.setText(c.getCodigo());
    }//GEN-LAST:event_jcClientItemStateChanged

    private void jcClientInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jcClientInputMethodTextChanged

    }//GEN-LAST:event_jcClientInputMethodTextChanged

    private void jcClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcClientKeyReleased

    }//GEN-LAST:event_jcClientKeyReleased

    private void btadfamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadfamActionPerformed
        FormCliente f = new FormCliente(new javax.swing.JFrame(), null,null,-1, "Adicionar Cliente", true);
        f.setVisible(true);
        support.uninstall();
        comboboxClient(jcClient);
    }//GEN-LAST:event_btadfamActionPerformed

    private void btedfamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btedfamActionPerformed
        FormCliente f = new FormCliente(new javax.swing.JFrame(), null,null,-1, "Adicionar Cliente", true);
        f.setVisible(true);
        support.uninstall();
        comboboxClient(jcClient);
    }//GEN-LAST:event_btedfamActionPerformed

    private void btdelfamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelfamActionPerformed
        Cliente i = (Cliente) jcClient.getSelectedItem();
        if (txtIdP.getText().trim().equals("")) {
//            if (new ProdutoJpaController(emf).existeFamilia(i) != 0) {
//                JOptionPane.showMessageDialog(this, "Esta Cliente nao pode ser apagado", "Atencao", JOptionPane.WARNING_MESSAGE);
//                return;
//            }
        } else {
            try {
                new ClienteJpaController(emf).destroy(i.getIdcliente());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Categoria apagada com Sucesso");
        }
        support.uninstall();
       comboboxClient(jcClient);
    }//GEN-LAST:event_btdelfamActionPerformed

    private void btadimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadimpActionPerformed
        FormModelo f = new FormModelo(new javax.swing.JFrame(), null, "Adicionar Modelo", true);
        f.setVisible(true);
        support2.uninstall();
        comboModelo(cbmodelo);
    }//GEN-LAST:event_btadimpActionPerformed

    private void btedimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btedimpActionPerformed
        FormModelo f = new FormModelo(new javax.swing.JFrame(), (Modelo) cbmodelo.getSelectedItem(), "Editar Modelo", true);
        f.setVisible(true);
       support2.uninstall();
        comboModelo(cbmodelo);
    }//GEN-LAST:event_btedimpActionPerformed

    private void btdelimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelimpActionPerformed
        Modelo i = (Modelo) cbmodelo.getSelectedItem();
        int ind = cbmodelo.getSelectedIndex();
        if (txtIdP.getText().trim().equals("")) {
            if (new ProdutoJpaController(emf).existeModelo(i) != 0) {
                JOptionPane.showMessageDialog(this, "Este Modelo esta em uso! Nao pode ser apagado", "Atencao", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            try {
                new ModeloJpaController(emf).destroy(i.getIdmodelo());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(FormProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Modelo apagado com Sucesso");
        }
        support2.uninstall();
        combobox(cbmodelo);
    }//GEN-LAST:event_btdelimpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormViatura dialog = new FormViatura(new javax.swing.JFrame(), p, t, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void combobox(JComboBox c) {
        List<Empresa> listaemp = new EmpresaJpaController(emf).findEmpresaEntities();
        c.removeAllItems();
        for (Empresa lista : listaemp) {
            c.addItem(lista);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadfam;
    private javax.swing.JButton btadimp;
    private javax.swing.JButton btdelfam;
    private javax.swing.JButton btdelimp;
    private javax.swing.JButton btedfam;
    private javax.swing.JButton btedimp;
    private javax.swing.JComboBox cbmodelo;
    private com.toedter.calendar.JDateChooser dent;
    private com.toedter.calendar.JDateChooser dsaida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcClient;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lbValidacao;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtcor;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
